### ISSUE TITLE
issue 2

### ISSUE THREAD

**Issue by ryankwilliams** [eduardocerqueira/demo#2]
Description about this issue.

**Comment by eduardocerqueira** [comment]
Hi @rwilliams5 

first of all thank you to report this issue and contribute to make demo better project, but I can't reproduce your issue. 

Maybe if you could describe more details and share the script to configure your environment would be nice! btw, have you heard about a Linux tool that allow you to share environment configurations with others and easily spin-up virtual machines in Openstack cloud?
